name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }} # Remote server's IP address
          username: ${{ secrets.SERVER_USERNAME }} # Remote server's username
          key: ${{ secrets.SERVER_PASSWORD }} # Use SSH private key for authentication
          script: |
            # Create directory if not exists
            mkdir -p /var/www/app1
            # Copy contents of 'dist' folder to '/var/www/app1/'
            rsync -avz --delete dist/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/var/www/app1/
